### ISSUE TITLE
[TCOTD2] Massive performance drops with the newly-added geometry outside

### ISSUE THREAD

**Issue by nashmuhandes** [Realm667/Re-Releases#152] opened 2023-02-07 09:49 UTC
@Tormentor667 please reduce the amount of lines used in the woods. The worst offender here is the road - it uses WAY too many lines (generating up to 30k vertices depending on where you're standing - dropping my FPS below 60 - completely unacceptable)

I don't think the amount of geo used here justifies the performance drop - it doesn't add that much to the visual language and presentation. It's just a road that most people won't even spend time to look at.

![image](https://user-images.githubusercontent.com/4926156/217210027-68bffd44-af77-495e-8d94-910e36453003.png)

![image](https://user-images.githubusercontent.com/4926156/217210232-88bbe844-ff42-4080-80dc-2cb0d7fb1bfc.png)

I would also consider breaking the line of sight between the various areas - for example, it's possible to see all the way to the church from the mansion - though I would recommend doing this on a separate commit, and very, very carefully, as it requires you to move entire sections of the map and may be subject to messing something up in the process

**Comment by nashmuhandes** [comment] 2023-02-07 09:52
![image](https://user-images.githubusercontent.com/4926156/217210956-6beab35c-11c9-4116-80d4-bcbbfe9b8c9b.png)

Absolutely unnecessary geometry here that just serves to drain FPS while not really making that much of an impact visually. :(

**Comment by nashmuhandes** [comment] 2023-02-07 14:22
![image](https://user-images.githubusercontent.com/4926156/217269109-c2d1551d-8d81-43eb-ad1f-b28a86ce5b6c.png)

From where the player is standing (in front of the mansion), looking towards the woods where the bonfire is - the engine is rendering both part of the swamp, as well as bits of the church waaaaaay on the other side of the map. To optimize this, the level needs to be altered so that there will be 1-sided lines blocking the rendering. For example:

![image](https://user-images.githubusercontent.com/4926156/217270758-feaa6f55-251f-4b93-b146-5039aad807ac.png)

**Comment by Tormentor667** [comment] 2023-02-07 17:56
I can take care of that. The problem is: With my hardware setup I simply do not notice any framedrops at all so it was or is hard for me to debug it. Will work on it as soon as you sign out.

**Comment by Tormentor667** [comment] 2023-02-08 19:18
Fixed in my latest commit.

**Closed by Tormentor667** 2023-02-08 19:18 UTC

**Comment by nashmuhandes** [comment] 2023-02-08 20:31
@Tormentor667 thanks, much better now, though the two swamp areas are still quite heavy on geometry. I'll take a closer look to suggest what can be improved in those areas a bit later when I have more time to put into it

**Comment by Tormentor667** [comment] 2023-02-08 22:00
Sure thing, I will take a closer look at this area after my vacation (will be back on Sunday evening)
