### ISSUE TITLE
[TCotD2] Different color for the Nightmare's blinding effect

### ISSUE THREAD

**Issue by Blue-Shadow** [Realm667/Re-Releases#140] opened 2023-02-03 00:40 UTC
When you get hit by the Nightmare, your screen goes white temporarily. I personally find the effect annoying. But what I find even more annoying, and discomforting to the eyes, is the chosen color. The game is generally dark, so your eyes are well adjusted to the darkness. Then you get hit by the monster, and suddenly everything becomes blinding white.

If this effect must be kept, I suggest the color be changed to black.

**Comment by nashmuhandes** [comment] 2023-02-03 11:05
Going to be blunt here, not a fan of the effect. :P

(this was another thing that was added during my absence, I wasn't even aware of it until I got hit by it)

If it must be kept in, the alpha of the effect should be turned way way waaaay down. Yes, as Blue Shadow said, this is very discomforting and _may_ cause seizures due to the extreme differences in screen brightness and in a very short burst, caused by the effect.

**Comment by Tormentor667** [comment] 2023-02-03 17:01
One way or another, the death sequence of the Sirene Nightmares must be something special, not only the typical red pain death.

**Comment by Blue-Shadow** [comment] 2023-02-08 02:59
> If it must be kept in, the alpha of the effect should be turned way way waaaay down.

Doing that, though, would defeat the purpose of momentarily blinding the player, which I'd imagine the intention behind the effect in the first place.

> One way or another, the death sequence of the Sirene Nightmares must be something special, not only the typical red pain death.

Well, there's currently a "spooky" visage which appears on the screen upon dying to one of them...

**Comment by Blue-Shadow** [comment] 2023-10-04 06:51
So what do we do with this? Change the color to black instead?

**Comment by Tormentor667** [comment] 2023-10-04 19:08
Black could work as well, I’d need to test it though. Could you just implement it for testing?

**Comment by Blue-Shadow** [comment] 2023-10-05 04:12
You can test it yourself easily by modifying [this](https://github.com/Realm667/Re-Releases/blob/master/tcotd2/zscript/player/TCOTDPlayer.zc#L141) line (change `White` to `Black`).

And here's the wiki page for A_SetBlend: https://zdoom.org/wiki/A_SetBlend

**Comment by Tormentor667** [comment] 2023-10-06 19:16
Thanks for pointing me towards this. In Black, the effect is much better, did it like that, closing this.

**Closed by Tormentor667** 2023-10-06 19:16 UTC
Labels: suggestion, tcotd2, gameplay
